-- Banco catálogo: contas, assinaturas e o índice de login (email -> conta).
-- Dados de negócio (Cliente, Empreendimento, cálculos etc.) NÃO ficam aqui — cada conta
-- tem seu próprio banco, provisionado por TenantProvisionamentoService com as migrations
-- de db/tenant.

CREATE TABLE tb_conta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_escritorio character varying(255) NOT NULL,
    criado_em timestamp(6) without time zone
);

CREATE TABLE tb_assinatura (
    conta_id bigint PRIMARY KEY REFERENCES tb_conta(id),
    plano character varying(255)
        CHECK (plano IN ('STARTER', 'PROFISSIONAL', 'ESCRITORIO')),
    status character varying(255) NOT NULL
        CHECK (status IN ('PENDENTE', 'ATIVA', 'EXPIRADA')),
    expira_em timestamp(6) without time zone,
    abacatepay_cobranca_id character varying(255),
    ultima_cobranca_confirmada_id character varying(255),
    criado_em timestamp(6) without time zone,
    atualizado_em timestamp(6) without time zone
);

-- Login busca por e-mail sem saber a conta ainda: resolve aqui qual banco de tenant
-- consultar antes de validar a senha (que fica no próprio banco do tenant).
CREATE TABLE tb_usuario_indice (
    email character varying(255) PRIMARY KEY,
    conta_id bigint NOT NULL REFERENCES tb_conta(id)
);
